# Generated by Django 4.2.1 on 2023-06-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='ano_lancamento',
            new_name='ano',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='genero',
        ),
        migrations.AlterField(
            model_name='filme',
            name='diretor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='filme',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
